### ISSUE TITLE
License Compatibility

### ISSUE THREAD

**Issue by vjkoskela** [java-json-tools/json-schema-core#34]
The project is licensed under both the Lesser General Public License (LGPLv3) and the Apache License v2 (ASL 2.0) as per the README.md file. However, the project depends on Rhino which is released under the Mozilla Public License (MPL) only (https://github.com/mozilla/rhino). I'm no lawyer, but I don't believe that ASL is compatible with MPL; while MPL is compatible with ASL it's not reciprocal. That is ASL projects cannot contain MPL, but MPL projects can contain ASL. Can you clarify to what extent this project is released under ASL?

**Comment by Capstan** [comment]
I'm not a lawyer either, but I, fortunately, have access to some good resources internally, and @renaudd helped clarify this for me. The relevant piece is in [MPL v2 §3.3 Distribution of a Larger Work](https://www.mozilla.org/en-US/MPL/2.0/#distribution-of-a-larger-work). We don't release the `Covered Software`, since we just provide our lib jars at Maven Central, and the Rhino folks provide their own lib jars. But were we to publish full jars, as a `Larger Work`, then, we would also be responsible for providing the source code form of the `Covered Software`.

Thus, in my current understanding ASL projects can depend on MPL projects, with the result being a combined licensure.

Given the licenses of all the component pieces is also stored in Maven Central, then one should be able to determine what licenses cover what parts of what larger work, so I believe we just advertise the license for this work and not that of our dependencies.
